apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  MONGO_INITDB_DATABASE: {{ .Values.mongodb.database.name }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.database.username }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.database.password }}