apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - {{ .Values.mongodb.persistence.accessMode }}
  storageClassName: {{ .Values.mongodb.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.storage }}