apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb-service
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      app: mongodb

  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector: {{- toYaml .Values.mongodb.nodeSelector | nindent 8 }}

      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.mongodb.service.targetPort }}

          envFrom:
            - configMapRef:
                name: mongodb-config

          volumeMounts:
            - name: mongodb-storage
              mountPath: {{ .Values.mongodb.mountPath }}

      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc