{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.hpa.server.targetDeployment }}
  minReplicas: {{ .Values.hpa.server.minReplicas }}
  maxReplicas: {{ .Values.hpa.server.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.server.targetCPUUtilizationPercentage }}
{{- end }}