apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: {{ .Values.server.service.type }}
  selector:
    app: server
  ports:
  - port: {{ .Values.server.service.port }}
    targetPort: {{ .Values.server.service.targetPort }}