apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  MONGO_URI: "mongodb://admin:password@mongodb-service:27017/Todo_App?authSource=admin"
  SECRET_KEY: "fmwe21s21wqwd"
  PORT: "5000"
